version: '3'
services:
    web:
        image: nginx:1.19-alpine
        working_dir: /src/app
        volumes:
            - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/logs/nginx:/var/log/nginx
            - ./docker/logs/lumen:/src/app/storage
            - .:/src
        ports:
            - 8080:80
        restart: always
        depends_on:
            - php
            - db
            - composer
            
    php:
        build: .
        restart: always
        working_dir: /src/app
        volumes:
            - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/src
            
    db:
        image: postgres:11.1-alpine
        restart: always
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USERNAME=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./docker/conf/postgres/:/docker-entrypoint-initdb.d/
    

    composer:
        image: composer
        working_dir: /src/app
        volumes:
            - .:/src
        command: install --ignore-platform-reqs
        
