version: '3'
services:
    web:
        image: nginx:1.19-alpine
        working_dir: /src/app
        volumes:
            - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/logs/nginx:/var/log/nginx
            - .:/src
        ports:
            - 80:80
            - 443:443
        restart: always
        depends_on:
            - db
            - cache
            - php

    php:
        build: .
        #image: hermsi/alpine-fpm-php:7.4
        restart: always
        working_dir: /src/app
        volumes:
            - ./docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/src
     

    node:
        image: node:12-alpine
        #command: npm install
     
    db:
        image: postgres:11.1-alpine
        restart: always
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USERNAME=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            #- ./docker/conf/postgres/:/docker-entrypoint-initdb.d/
            - ./docker/conf/postgres/data/:/var/lib/postgresql/data/

    
    cache:
        image: redis:6.2-alpine
        restart: always
        #ports:
            #- 6379:6379
          
