version: '3'
services:
    web:
        image: nginx:1.19-alpine
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/logs:/var/log/nginx
            - ./src:/app
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
        env_file:
            - .env
            
    php:
        build: .
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./src:/app
            
    composer:
        image: composer
        volumes:
            - ./src:/app
        command: install --ignore-platform-reqs
        
    db:
        image: postgres:11.1-alpine
        restart: always
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USERNAME=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
    
